### PR TITLE
Move most of the readme to the Sphinx documentation

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by rm-hull** [comment]
@thijstriemstra if I build the sphinx docs locally (`make html` in the docs directory), I get a table of contents in the left-hand panel, but not on the readthedocs version... do you know why?

screen shot 2016-11-26 at 21 30 07

screen shot 2016-11-26 at 21 30 21

**Comment by thijstriemstra** [comment]
rtd uses a different theme, alabaster i think?

**Comment by rm-hull** [comment]
It wasnt the theme I was asking about (not too fussed about that), but was a bit puzzled as to why there is no table of contents on the rtd version. I would've assumed both the local makefile and rtd would be using the docs/conf.py to generate the docs, and that (apart from the themes) they would generate identical content.

**Comment by rm-hull** [comment]
Ok, so I split the docs up into separate files & did a small bit of tidy up too - looks better now

**Pull request merged**
