### PR TITLE
Add travis and tox configurations

### PR DESCRIPTION
**Pull request by thijstriemstra**

### CODE REVIEW

**Comment by thijstriemstra** [comment]
@rm-hull any idea what this is about? https://travis-ci.org/rm-hull/max7219/jobs/175573779#L178

**Comment by rm-hull** [comment]
I was googling that about 2hrs ago, and saw this: http://stackoverflow.com/questions/8295644/pypi-userwarning-unknown-distribution-option-install-requires

so pip uses it but distutils doesnt

**Comment by rm-hull** [comment]
thanks for all the PR's you're submitting ... you're on fire !  

:)

**Comment by thijstriemstra** [comment]
@rm-hull hehe, if just finished a project this week (using your library!) that went really well, but I didn't have any time to code so I'm making up now.

**Comment by thijstriemstra** [comment]
Ah yes, @rm-hull you need to change https://github.com/rm-hull/max7219/blob/master/setup.py#L4 and https://github.com/rm-hull/ssd1306/blob/master/setup.py#L4 into:

```
from setuptools import setup
```

**Pull request merged**
