### PR TITLE
Convert readme to rst

### PR DESCRIPTION
**Pull request by thijstriemstra**
refs #35

### CODE REVIEW

**Comment by rm-hull** [comment]
Don't know if you can see https://readthedocs.org/projects/max7219/builds/4467998/ (output as below), but the build failed with **imgmath**, so I just reverted back to **pngmath** and now the docs are generating ok - http://max7219.readthedocs.io/

```
Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/max7219/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/max7219/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/max7219/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
ExtensionError: Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)

Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
```

**Comment by thijstriemstra** [comment]
that's a really old version of Sphinx @rm-hull. If you use the latest 1.4.x you'll see the warning. But I guess this is a better solution, being able to support both.

**Comment by thijstriemstra** [comment]
or maybe even better, simply remove the reference, we're not using imgmath or pngmath afaik.

**Comment by rm-hull** [comment]
Presumably _readthedocs_ selects the sphinx version when it builds, but you're right: i'll just remove the reference :)

**Pull request merged**
